"""Pobla la tabla ree_funciones con las actividades de Red Eléctrica."""
import os
import psycopg2
from dotenv import load_dotenv

load_dotenv()

FUNCIONES = [
    # TRANSPORTISTA
    ("transportista", "Desarrollar y ampliar la red de transporte",
     "Garantizar que la red crece y se refuerza conforme a criterios homogéneos, coherentes y de mínimo coste.",
     "Art. 36.1 y 36.3.f) Ley 24/2013; art. 6.1 RD 1955/2000",
     "red de transporte,ampliación red,refuerzo red,desarrollo red,planificación transporte"),
    ("transportista", "Ejecutar la planificación aprobada de la red de transporte",
     "Construir las actuaciones incluidas en la planificación y en los planes de inversión aprobados.",
     "Art. 34.4 y art. 36.3.f) Ley 24/2013; art. 11 RD 1047/2013",
     "planificación red,plan de inversión,construcción instalaciones transporte"),
    ("transportista", "Construir nuevas instalaciones de transporte",
     "Líneas, subestaciones, transformadores, posiciones, elementos de control, protecciones, comunicaciones y demás activos de la red de transporte.",
     "Art. 34.1 Ley 24/2013; art. 5 RD 1955/2000; art. 1 RD 1047/2013",
     "línea de transporte,subestación,transformador,LAT,instalación de transporte,construcción línea"),
    ("transportista", "Mantener las instalaciones de transporte",
     "Ejecutar los planes de mantenimiento y conservar las instalaciones en condiciones adecuadas.",
     "Art. 36.3.a) y j) Ley 24/2013; art. 7.2.a) RD 1955/2000",
     "mantenimiento red transporte,conservación instalaciones,mantenimiento preventivo"),
    ("transportista", "Maniobrar las instalaciones de transporte",
     "Realizar la maniobra material de instalaciones propias, siguiendo las instrucciones del operador del sistema.",
     "Art. 36.3.c) y l) Ley 24/2013; art. 7.2.a) RD 1955/2000",
     "maniobra instalaciones,operación red transporte"),
    ("transportista", "Prestar el servicio de transporte de forma regular y continua",
     "Permitir la transmisión de electricidad por la red de transporte con los niveles de calidad exigibles.",
     "Art. 36.3.j) Ley 24/2013; art. 4 RD 1955/2000",
     "servicio transporte eléctrico,calidad suministro,transmisión electricidad"),
    ("transportista", "Facilitar el uso de la red por terceros",
     "Permitir tránsitos de energía y uso de las redes por sujetos autorizados en condiciones no discriminatorias.",
     "Art. 36.3.k) Ley 24/2013; art. 7.2.b) RD 1955/2000",
     "acceso terceros,tránsito energía,uso red transporte,no discriminación"),
    ("transportista", "Otorgar el permiso de conexión a la red de transporte",
     "Evaluar la viabilidad física/técnica de conexión al punto de red y emitir el permiso de conexión como titular de la red.",
     "Art. 36.3.i) Ley 24/2013; art. 15 RD 1183/2020",
     "permiso de conexión,conexión red transporte,viabilidad técnica conexión"),
    ("transportista", "Valorar la viabilidad de conexión",
     "Analizar si el punto solicitado permite la conexión técnica de la instalación.",
     "Art. 11.1 RD 1183/2020",
     "viabilidad conexión,estudio conexión,punto de conexión"),
    ("transportista", "Suscribir contratos técnicos de acceso",
     "Formalizar con consumidores, generadores o distribuidores conectados a la red las condiciones técnicas de relación con la red.",
     "Art. 21 RD 1183/2020",
     "contrato técnico acceso,condiciones técnicas red,contrato acceso red"),
    ("transportista", "Preparar y presentar planes de inversión anuales y plurianuales",
     "Someter a aprobación administrativa los planes de inversión de la red de transporte.",
     "Art. 34.4 Ley 24/2013; art. 11 RD 1047/2013",
     "plan de inversión,plan anual inversión,plan plurianual inversión,RAP"),
    ("transportista", "Informar al operador del sistema",
     "Aportar la información necesaria para que el operador pueda cumplir sus funciones.",
     "Art. 36.3.h) Ley 24/2013; art. 7.2.d) RD 1955/2000",
     "información operador sistema,coordinación operador transportista"),
    ("transportista", "Garantizar no discriminación entre usuarios de la red de transporte",
     "Tratar de forma objetiva a los usuarios o categorías de usuarios.",
     "Art. 36.3.g) Ley 24/2013",
     "no discriminación usuarios red,trato objetivo usuarios"),
    ("transportista", "Realizar estudios de conexión",
     "El titular de la red percibe pagos por estudios de conexión; el gestor de la red percibe pagos por estudios de acceso.",
     "Art. 27 RD 1047/2013",
     "estudio de conexión,pago estudio conexión,estudio de acceso"),
    ("transportista", "Asegurar disponibilidad de la red",
     "Mantener las instalaciones disponibles; la retribución incorpora un incentivo/penalización ligado a disponibilidad.",
     "Arts. 20 y 21 RD 1047/2013",
     "disponibilidad red,incentivo disponibilidad,retribución disponibilidad"),
    # OPERADOR DEL SISTEMA
    ("operador", "Garantizar la continuidad y seguridad del suministro",
     "Es la función principal del operador del sistema.",
     "Art. 30.1 Ley 24/2013",
     "seguridad suministro,continuidad suministro,garantía suministro,Art.64"),
    ("operador", "Coordinar el sistema de producción y transporte",
     "Coordinar generación, transporte y funcionamiento global del sistema eléctrico.",
     "Art. 30.1 Ley 24/2013",
     "coordinación sistema eléctrico,coordinación generación transporte"),
    ("operador", "Prever y controlar la garantía de abastecimiento",
     "Analizar la suficiencia del sistema a corto y medio plazo.",
     "Art. 30.2.a) Ley 24/2013",
     "garantía abastecimiento,suficiencia sistema,capacidad instalada"),
    ("operador", "Prever la demanda eléctrica",
     "Estimar demanda, uso del parque de generación y condiciones hidrológicas/eólicas.",
     "Art. 30.2.b) Ley 24/2013",
     "previsión demanda,estimación demanda eléctrica,demanda del sistema"),
    ("operador", "Coordinar planes de mantenimiento de transporte y generación",
     "Compatibilizar indisponibilidades de red y generación para garantizar seguridad.",
     "Art. 30.2.d) Ley 24/2013",
     "coordinación mantenimiento,indisponibilidad red,programa mantenimiento"),
    ("operador", "Establecer medidas de fiabilidad del sistema",
     "Definir medidas de seguridad y fiabilidad que afectan a elementos necesarios del sistema eléctrico.",
     "Art. 30.2.e) Ley 24/2013",
     "fiabilidad sistema,seguridad sistema eléctrico,criterios seguridad"),
    ("operador", "Definir planes de reposición del servicio",
     "Preparar y coordinar planes de maniobra para recuperar el suministro tras fallos generales.",
     "Art. 30.2.e) Ley 24/2013; art. 6.2.g) RD 1955/2000",
     "reposición servicio,plan reposición,recuperación suministro,black start"),
    ("operador", "Impartir instrucciones de operación de la red de transporte en tiempo real",
     "Ordenar maniobras y actuaciones operativas para mantener el sistema seguro.",
     "Art. 30.2.f) y l) Ley 24/2013",
     "instrucciones operación,tiempo real,maniobra operativa,despacho"),
    ("operador", "Programar el funcionamiento de instalaciones de producción",
     "Programar generación conforme a mercados, bilaterales y necesidades de seguridad.",
     "Art. 30.2.k) Ley 24/2013",
     "programación generación,programa diario,programa operación,PVP"),
    ("operador", "Gestionar mercados de servicios de ajuste",
     "Activar y gestionar servicios necesarios para mantener frecuencia, balance y seguridad.",
     "Art. 30.2.k) y l) Ley 24/2013",
     "servicios de ajuste,regulación frecuencia,banda de regulación,reserva potencia,balance"),
    ("operador", "Liquidar servicios de ajuste, garantía de suministro y desvíos",
     "Calcular y comunicar pagos/cobros vinculados a servicios de ajuste, disponibilidad y desvíos.",
     "Art. 30.2.m) y n) Ley 24/2013",
     "liquidación servicios ajuste,liquidación desvíos,garantía suministro,LIQ/DE"),
    ("operador", "Gestionar interconexiones internacionales",
     "Determinar capacidad de uso, gestionar intercambios y tránsitos internacionales.",
     "Art. 30.2.h) Ley 24/2013; art. 6.2.e) y f) RD 1955/2000",
     "interconexión internacional,capacidad interconexión,intercambios internacionales,tránsito internacional"),
    ("operador", "Otorgar el permiso de acceso a la red de transporte",
     "Como gestor de la red de transporte, valora capacidad de acceso y emite el permiso de acceso.",
     "Art. 37.2 Ley 24/2013; art. 11.1 y art. 15 RD 1183/2020",
     "permiso de acceso,acceso red transporte,capacidad de acceso,nudo de acceso"),
    ("operador", "Actuar como punto de contacto único en acceso y conexión",
     "En el procedimiento conjunto, el gestor de red canaliza la tramitación frente al solicitante.",
     "Art. 5 RD 1183/2020",
     "punto de contacto,ventanilla única acceso conexión,procedimiento conjunto"),
    ("operador", "Publicar capacidad de acceso en los nudos",
     "Mantener plataformas web con información sobre capacidad disponible.",
     "Art. 33.9 Ley 24/2013; art. 5.3 y 5.4 RD 1183/2020",
     "capacidad disponible nudos,mapa capacidad,publicación capacidad acceso"),
    ("operador", "Elaborar propuestas para la planificación de la red",
     "Proponer soluciones para que la red pueda atender la demanda futura de transporte al menor coste y con fiabilidad.",
     "Art. 30.2.q) Ley 24/2013; art. 6.2.b) RD 1955/2000",
     "propuesta planificación,planificación indicativa,planificación vinculante,necesidades red"),
    ("operador", "Colaborar en la evaluación de los planes de inversión del transportista",
     "Informar o colaborar con Administración y CCAA sobre planes de inversión.",
     "Art. 30.2.p) Ley 24/2013; art. 13.3 RD 1047/2013",
     "evaluación plan inversión,colaboración administración planes inversión"),
    ("operador", "Gestionar información del sistema y de los agentes",
     "Recibir datos de mercado, bilaterales, explotación, medidas y operación.",
     "Art. 30.2.i), r), t), z) Ley 24/2013; art. 6.2.h) e i) RD 1955/2000",
     "gestión información sistema,datos mercado,medidas sistema,transparencia sistema"),
    ("operador", "Responsabilidad del sistema de medidas",
     "Velar por el buen funcionamiento del sistema de medidas y actuar como encargado de lectura en puntos frontera.",
     "Art. 30.2.x) Ley 24/2013",
     "sistema de medidas,encargado lectura,punto frontera,telemedida"),
    ("operador", "Recabar y gestionar información sobre calidad de servicio en transporte",
     "Informar a Administraciones y organismos sobre calidad de servicio en la red de transporte.",
     "Art. 30.2.y) Ley 24/2013",
     "calidad servicio transporte,indicadores calidad,continuidad suministro transporte"),
    ("operador", "Comunicar anomalías, fraudes o alteraciones de los procesos de operación",
     "Poner en conocimiento de autoridades competentes comportamientos anómalos.",
     "Art. 30.2.aa) y ab) Ley 24/2013",
     "anomalía operación,fraude sistema eléctrico,comunicación autoridades,REMIT"),
]

conn = psycopg2.connect(os.environ["DATABASE_URL"])
cur = conn.cursor()
cur.execute("DELETE FROM ree_funciones")
for f in FUNCIONES:
    cur.execute(
        "INSERT INTO ree_funciones (categoria, actividad, descripcion, base_legal, keywords) "
        "VALUES (%s, %s, %s, %s, %s)",
        f,
    )
conn.commit()
print(f"Insertadas {len(FUNCIONES)} funciones de Red Eléctrica.")
conn.close()
